services:
  - type: web
    name: tu-app-reflex
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: reflex run --env prod
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2